include: package:lints/recommended.yaml

linter:
  rules:
    prefer_function_declarations_over_variables: false

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
