// Regenerates `lib/src/utils/unicode_width.dart` from the Unicode Character
// Database.
//
//   dart run script/gen_unicode_width.dart [version]
//
// Version defaults to the one the checked-in table was built from. Passing an
// older one is how the rules below were confirmed: 12.1.0 reproduces the table
// this repository carried under the name `unicode_v11.dart`, range for range,
// which is what established that the file held 12.1 data rather than the 11.0
// its name and its `version` field both claimed.
//
// Only the tables are generated. The lookup itself is hand-written and lives
// in the emitted file's tail.

import 'dart:convert';
import 'dart:io';

/// The version regenerated when none is named.
const _defaultVersion = '16.0.0';

const _outputPath = 'lib/src/utils/unicode_width.dart';

Future<void> main(List<String> args) async {
  final version = args.isEmpty ? _defaultVersion : args.first;
  stderr.writeln('Fetching UCD $version');

  final eastAsian = await _fetch(
    'https://www.unicode.org/Public/$version/ucd/EastAsianWidth.txt',
  );
  final categories = await _fetch(
    'https://www.unicode.org/Public/$version/ucd/extracted/'
    'DerivedGeneralCategory.txt',
  );
  final emoji = await _fetch(
    'https://www.unicode.org/Public/$version/ucd/emoji/emoji-data.txt',
  );

  // A character takes no column when it is a mark or a format character.
  //
  // Two departures from the category data, both from the wcwidth this lookup
  // descends from: SOFT HYPHEN is `Cf` but is printed, and Hangul Jamo medial
  // and final forms are `Lo` but compose onto the preceding syllable.
  final combining = _codePoints(categories, const {'Mn', 'Me', 'Cf'})
    ..remove(0x00AD)
    ..addAll(_range(0x1160, 0x11FF));

  // Wide is East Asian Wide or Fullwidth, less anything already zero: the two
  // properties overlap (the Japanese voiced sound marks are `W` *and* `Mn`),
  // and a mark that occupies a column would push the rest of its line off the
  // grid.
  final wide = _codePoints(eastAsian, const {'W', 'F'})
    ..removeAll(combining);

  // The code points a font is expected to draw in colour without being asked.
  // The renderer needs them because it rasterises a glyph once and tints it
  // when it draws, which turns a colour glyph into a silhouette.
  final emojiPresentation = _codePoints(emoji, const {'Emoji_Presentation'});

  final out = File(_outputPath);
  out.writeAsStringSync(_emit(version, combining, wide, emojiPresentation));
  stderr.writeln('Wrote ${out.path}');
}

Future<String> _fetch(String url) async {
  final client = HttpClient();
  try {
    final res = await (await client.getUrl(Uri.parse(url))).close();
    if (res.statusCode != 200) {
      throw HttpException('HTTP ${res.statusCode}', uri: Uri.parse(url));
    }
    // Awaited inside the try, so the body is drained before `close()` runs.
    return await res.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}

/// Every code point in [text] whose property value is in [wanted].
///
/// Both files share the `start[..end] ; value # comment` line format.
Set<int> _codePoints(String text, Set<String> wanted) {
  final out = <int>{};

  for (final rawLine in const LineSplitter().convert(text)) {
    final line = rawLine.split('#').first.trim();
    if (line.isEmpty) continue;

    final parts = line.split(';');
    if (parts.length < 2) continue;
    if (!wanted.contains(parts[1].trim())) continue;

    final bounds = parts[0].trim().split('..');
    final start = int.parse(bounds.first, radix: 16);
    final end = int.parse(bounds.last, radix: 16);
    out.addAll(_range(start, end));
  }

  return out;
}

Iterable<int> _range(int start, int end) sync* {
  for (var i = start; i <= end; i++) {
    yield i;
  }
}

/// [codePoints] within `[low, high]`, as ascending non-adjacent ranges.
List<List<int>> _ranges(Set<int> codePoints, int low, int high) {
  final sorted = codePoints.where((cp) => cp >= low && cp <= high).toList()
    ..sort();

  final out = <List<int>>[];
  for (final cp in sorted) {
    if (out.isNotEmpty && cp == out.last[1] + 1) {
      out.last[1] = cp;
    } else {
      out.add([cp, cp]);
    }
  }
  return out;
}

String _emit(
  String version,
  Set<int> combining,
  Set<int> wide,
  Set<int> emojiPresentation,
) {
  final buf = StringBuffer()
    ..writeln('// GENERATED by script/gen_unicode_width.dart. DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Unicode $version.')
    ..writeln('//')
    ..writeln('// Regenerate with:')
    ..writeln('//')
    ..writeln('//   dart run script/gen_unicode_width.dart $version')
    ..writeln('//')
    ..writeln('// The rules the tables are derived under are documented there.')
    ..writeln("// ignore_for_file: constant_identifier_names")
    ..writeln()
    ..writeln("import 'dart:typed_data';")
    ..writeln();

  void table(String name, List<List<int>> ranges, String doc) {
    buf
      ..writeln('/// $doc')
      ..writeln('const $name = [');
    for (final r in ranges) {
      buf.writeln(
        '  [0x${r[0].toRadixString(16).toUpperCase().padLeft(4, '0')}, '
        '0x${r[1].toRadixString(16).toUpperCase().padLeft(4, '0')}],',
      );
    }
    buf
      ..writeln('];')
      ..writeln();
  }

  table(
    'BMP_COMBINING',
    _ranges(combining, 0, 0xFFFF),
    'Zero-width code points inside the BMP.',
  );
  table(
    'HIGH_COMBINING',
    _ranges(combining, 0x10000, 0x10FFFF),
    'Zero-width code points above the BMP.',
  );
  table(
    'BMP_WIDE',
    _ranges(wide, 0, 0xFFFF),
    'Two-column code points inside the BMP.',
  );
  table(
    'HIGH_WIDE',
    _ranges(wide, 0x10000, 0x10FFFF),
    'Two-column code points above the BMP.',
  );
  table(
    'BMP_EMOJI_PRESENTATION',
    _ranges(emojiPresentation, 0, 0xFFFF),
    'Code points drawn in colour by default, inside the BMP.',
  );
  table(
    'HIGH_EMOJI_PRESENTATION',
    _ranges(emojiPresentation, 0x10000, 0x10FFFF),
    'Code points drawn in colour by default, above the BMP.',
  );

  buf.write(_runtime.replaceFirst('@version@', version));
  return buf.toString();
}

/// The lookup, copied verbatim into the generated file.
const _runtime = r'''
/// Widths for the whole BMP, so the common case is one array read.
///
/// Above the BMP is rare enough to pay for a binary search instead of another
/// megabyte of table.
final table = buildTable();

Uint8List buildTable() {
  final table = Uint8List(65536);
  table.fillRange(0, table.length, 1);
  table[0] = 0;
  table.fillRange(1, 32, 0);
  table.fillRange(0x7f, 0xa0, 0);
  for (var r = 0; r < BMP_COMBINING.length; ++r) {
    table.fillRange(BMP_COMBINING[r][0], BMP_COMBINING[r][1] + 1, 0);
  }
  for (var r = 0; r < BMP_WIDE.length; ++r) {
    table.fillRange(BMP_WIDE[r][0], BMP_WIDE[r][1] + 1, 2);
  }
  return table;
}

bool bisearch(int ucs, List<List<int>> data) {
  var min = 0;
  var max = data.length - 1;
  int mid;
  if (ucs < data[0][0] || ucs > data[max][1]) {
    return false;
  }
  while (max >= min) {
    mid = (min + max) >> 1;
    if (ucs > data[mid][1]) {
      min = mid + 1;
    } else if (ucs < data[mid][0]) {
      max = mid - 1;
    } else {
      return true;
    }
  }
  return false;
}

/// How many columns a code point occupies.
class UnicodeWidth {
  /// The UCD release the tables above were generated from.
  final version = '@version@';

  int wcwidth(int codePoint) {
    if (codePoint < 32) return 0;
    if (codePoint < 127) return 1;
    if (codePoint < 65536) return table[codePoint];
    if (bisearch(codePoint, HIGH_COMBINING)) return 0;
    if (bisearch(codePoint, HIGH_WIDE)) return 2;
    return 1;
  }

  /// Whether a font is expected to draw [codePoint] in colour without being
  /// asked to. Nothing below U+2000 is, so ordinary text answers on a compare.
  bool hasEmojiPresentation(int codePoint) {
    if (codePoint < 0x2000) return false;
    if (codePoint < 65536) return bisearch(codePoint, BMP_EMOJI_PRESENTATION);
    return bisearch(codePoint, HIGH_EMOJI_PRESENTATION);
  }
}

final unicodeWidth = UnicodeWidth();
''';
